name: Build Docker Image
on:
  push:
    branches:
      - main
jobs:
    build:
      name: push docker image to docker hub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: login to docker hub
          id: docker-hub
          env:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_PASSWORD}}
          run: |
            echo $username
            echo $password
            docker login -u gh204688 -p Fourteen19!
        - name: build the docker image
          id: build-docker-image
          run: |
            ls -la 
            docker build . -f dockerfile -t ${{secrets.DOCKERHUB_USERNAME}}/demo-devops:latest
        - name: push the docker image
          id: push-docker-image
          run: docker push ${{secrets.DOCKERHUB_USERNAME}}/demo-devops:latest
